### ISSUE TITLE
Device mode - Switching banks displays text from previous bank

### ISSUE THREAD

**Issue by reflekshun** [teotigraphix/Maschine4Bitwig#51]
In Device Mode, switching banks displays bank title text on Maschine (MKII) from the bank it is switching from, rather than the one you have moved to. If not possible to fix, may be better that the text doesn't show when scrolling through banks, for faster workflow.

**Comment by teotigraphix** [comment]
Nope this is a bug and I didn't notice it.

**Comment by teotigraphix** [comment]
Fixed.
