### ISSUE TITLE
Scale Mode - 3rd triggers two pads

### ISSUE THREAD

**Issue by reflekshun** [teotigraphix/Maschine4Bitwig#53]
Third of every scale in scale mode triggers and occupies two pads - both pads light up white when pressing either, and play the same note: 3rd of the scale.

Resolving this will free up a pad space and increase ease of playing.

**Comment by teotigraphix** [comment]
This is a feature form the Push and yes on 16 pads it doesn't make much sense but there is a configuration change you can make to change it to 4ths.

![seq](https://cloud.githubusercontent.com/assets/226417/9788695/67d1eefa-5799-11e5-82bf-0c611c0d0ac7.JPG)

Select Seqnt^ to utilize all pads. (project settings on the right side panel).

**Comment by teotigraphix** [comment]
I will change the default to seq so it's uses all the pads.

**Comment by reflekshun** [comment]
Nice Change :)
